### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by vigilancetrent** [AI4Finance-Foundation/FinRL#1045]
Alpaca successfully connected
Traceback (most recent call last):
  File "C:\Users\louis\Desktop\SUPERAI\FinRL-master\FinRL-master\STOCK.py", line 179, in <module>
    train(
  File "C:\Users\louis\Desktop\SUPERAI\FinRL-master\FinRL-master\finrl\meta\paper_trading\common.py", line 749, in train
    trained_model = agent.train_model(
  File "C:\Users\louis\Desktop\SUPERAI\FinRL-master\FinRL-master\finrl\meta\paper_trading\common.py", line 634, in train_model
    train_agent(model)
  File "C:\Users\louis\Desktop\SUPERAI\FinRL-master\FinRL-master\finrl\meta\paper_trading\common.py", line 426, in train_agent
    agent.states = env.reset()[np.newaxis, :]
TypeError: tuple indices must be integers or slices, not tuple

**Comment by AjinkyaBankar** [comment]
Getting the same error. Were you able to solve this?

**Comment by TheStoneMX** [comment]
Getting the same error, I tried this:

agent.states = env.reset()[0][np.newaxis, :]

but does not work.... any help ?
