### ISSUE TITLE
finrl/applications/stock_trading/ensemble_stock_trading.py it give an error for pandas library error accorginto i loaded all library.

### ISSUE THREAD

**Issue by omerfirat** [AI4Finance-Foundation/FinRL#1052]
Hi, it give an error like below inbacktest_plot  when iy run finrl/applications/stock_trading/ensemble_stock_trading.py file,

I install all environment like setup.py and requirements.txt

i think tisi is error is related with pandas version but , if back to old version get an error for every library please rerun and fix all libraries.

Traceback (most recent call last):
  File "C:\Users\Onec\Desktop\ömer\FinRL-master\finrl\applications\stock_trading\ensemble_stock_trading.py", line 195, in <module>
    main()
  File "C:\Users\Onec\Desktop\ömer\FinRL-master\finrl\applications\stock_trading\ensemble_stock_trading.py", line 186, in main
    backtest_plot(
  File "C:\Python310\lib\site-packages\finrl\plot.py", line 96, in backtest_plot
    pyfolio.create_full_tear_sheet(
  File "C:\Python310\lib\site-packages\pyfolio\tears.py", line 201, in create_full_tear_sheet
    create_returns_tear_sheet(
  File "C:\Python310\lib\site-packages\pyfolio\plotting.py", line 54, in call_w_context
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pyfolio\tears.py", line 496, in create_returns_tear_sheet
    plotting.show_perf_stats(returns, benchmark_rets,
  File "C:\Python310\lib\site-packages\pyfolio\plotting.py", line 648, in show_perf_stats
    for stat, value in perf_stats[column].iteritems():
  File "C:\Python310\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'

**Comment by AjinkyaBankar** [comment]
Thanks! This worked, but I had to modify line# 648 of the `plotting.py` as `for stat, value in perf_stats[column].items():`.

**Comment by zhumingpassional** [comment]
@AjinkyaBankar 
could you pls submit a PR?

**Comment by notBradPitt** [comment]
I'd love to submit a PR to Pyfolio, but the repository hasn't been updated for a while. Should I just make a fork and change the requirements here to reflect the updated code?

**Comment by zhumingpassional** [comment]
@notBradPitt 
what do you mean by "change the requirements"? only change the requirements.txt?

**Comment by notBradPitt** [comment]
@zhumingpassional
The fix involves modifying Pyfolio package, which I don't think will be updated or accept PR. So I'm asking if I could just fork the Pyfolio package and change the requirement.txt to use the fork, e.g.

```
Pyfolio git+https://github.com/notbradpitt/pyfolio
```

instead of 

```
pyfolio
```

in the requirements.txt

**Comment by zhumingpassional** [comment]
I do not accept the PR.
I suggest users to revise it locally since it is caused by the pyfio package.

**Comment by zhumingpassional** [comment]
I suggest users to revise the pyfio package locally
That plot function is not necessary, and can be replace by others.
I also suggest  to use other plot functions in finrl.plot, or write your own functions.

**Comment by VishnuRaghavan** [comment]
Just install pyfolio-reloaded package from pip.

**Comment by patrickzha** [comment]
"if not hasattr(pd.Series, "iteritems"):
    pd.Series.iteritems = pd.Series.items" also worked for me
