### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by oddyolau** [AI4Finance-Foundation/FinRL#1293]
**Describe the bug**
when install, meet the problem blew:
module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

**Expected behavior**
please update

**Desktop (please complete the following information):**
 - OS: MacOS15.1
 - Version python12.7

**Comment by ellr** [comment]
I ran into the same issue. You'll need to switch back to Python 3.10 to get around the error. Unfortunately on Python 3.12 the installation fails with the error you described. But on 3.11 it tells you that your python version is too new.

**Comment by zhumingpassional** [comment]
pls try the newest version. I updated it.

**Comment by gbattl** [comment]
I just installed and having the same issue.. is it the main branch that was updated?
Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0] on linux

Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.8)
  Using cached pyfolio-0.9.2.tar.gz (91 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-yqjm44r4/pyfolio_2eddaafb18ba47bc91d71b7cd80e97e9/versioneer.py:468: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yqjm44r4/pyfolio_2eddaafb18ba47bc91d71b7cd80e97e9/setup.py", line 71, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-yqjm44r4/pyfolio_2eddaafb18ba47bc91d71b7cd80e97e9/versioneer.py", line 1407, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-yqjm44r4/pyfolio_2eddaafb18ba47bc91d71b7cd80e97e9/versioneer.py", line 1341, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-yqjm44r4/pyfolio_2eddaafb18ba47bc91d71b7cd80e97e9/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by zhumingpassional** [comment]
git clone

**Comment by axelsnoski** [comment]
> git clone

It's not working still:
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.8)
  Downloading pyfolio-0.9.2.tar.gz (91 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/dz/zwj24rc16s318hzxzydyrw140000gn/T/pip-install-9czixw8d/pyfolio_a682a93b18c0402dac2836dd6f55be60/versioneer.py:468: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dz/zwj24rc16s318hzxzydyrw140000gn/T/pip-install-9czixw8d/pyfolio_a682a93b18c0402dac2836dd6f55be60/setup.py", line 71, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/zwj24rc16s318hzxzydyrw140000gn/T/pip-install-9czixw8d/pyfolio_a682a93b18c0402dac2836dd6f55be60/versioneer.py", line 1407, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/dz/zwj24rc16s318hzxzydyrw140000gn/T/pip-install-9czixw8d/pyfolio_a682a93b18c0402dac2836dd6f55be60/versioneer.py", line 1341, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dz/zwj24rc16s318hzxzydyrw140000gn/T/pip-install-9czixw8d/pyfolio_a682a93b18c0402dac2836dd6f55be60/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
