### ISSUE TITLE
main.py - Could not broadcast input array from shape

### ISSUE THREAD

**Issue by zywang624** [AI4Finance-Foundation/FinRL#206]
I run "python main.py --mode=train" as mentioned in README, and it reports that the following error.
![4](https://user-images.githubusercontent.com/41494634/113473089-03873880-949a-11eb-98a6-aaa179b54883.png)

**Comment by b-tank1** [comment]
Does this actually impact anything? I'm able to run the notebooks despite this error

**Comment by Wisgon** [comment]
Same problem. @b-tank1 Which notebook do you run?

**Comment by peacemind** [comment]
I get same error when running "python3 main.py --mode=train" on my Ubuntu 20.04 (Python 3.8):
The following show part of the error messages:
/////////////////////
Shape of DataFrame: (156457, 8)
==============Start Feature Engineering===========
Successfully added technical indicators
Successfully added turbulence index
Traceback (most recent call last):
File "main.py", line 52, in
main()
File "main.py", line 38, in main
finrl.autotrain.training.train_one()
File "/home/happy/gitprojects/rl/FinRL-Library/finrl/autotrain/training.py", line 67, in train_one
env_train, _ = e_train_gym.get_sb_env()
File "/home/happy/gitprojects/rl/FinRL-Library/finrl/env/env_stocktrading.py", line 379, in get_sb_env
obs = e.reset()
File "/home/happy/miniconda3/envs/finrl-venv/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
self._save_obs(env_idx, obs)
File "/home/happy/miniconda3/envs/finrl-venv/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (292,) into shape (301,)

/////////
Any ideas how to fix this error?

**Comment by RomanZWang** [comment]
#222

**Comment by zhumingpassional** [comment]
Some stock may not have data in the full-time period, so that the length is wrong. You can try remove some stock, or revise the start-end date.
