### ISSUE TITLE
Errors running python main.py --mode=train from docker+notebook

### ISSUE THREAD

**Issue by devm21** [AI4Finance-Foundation/FinRL#216]
Steps to reproduce:
```
./docker/bin/build_container.sh
./docker/bin/start_notebook.sh
```
Open the notebook, add terminal, run 
```
pip install stable-baselines3[extra]
python main.py --mode=train
```

Errors: 
root@af475e1422f9:/home# python main.py --mode=train
/opt/conda/lib/python3.6/site-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; multipliers will not be applied'
  Shape of DataFrame:  (156457, 8)
==============Start Feature Engineering===========
Successfully added technical indicators
Successfully added turbulence index
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "/home/finrl/autotrain/training.py", line 67, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "/home/finrl/env/env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: cannot copy sequence with size 292 to array axis with dimension 301
```

Then after `pip install zipline`, errors:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yfinance 0.1.55 requires pandas>=0.24, but you have pandas 0.22.0 which is incompatible.
seaborn 0.11.1 requires pandas>=0.23, but you have pandas 0.22.0 which is incompatible.
Successfully installed Logbook-1.5.3 bcolz-1.2.1 bottleneck-1.3.2 cached-property-1.5.2 h5py-3.1.0 intervaltree-3.1.0 iso3166-1.0.1 iso4217-1.6.20180829 lru-dict-1.1.7 multipledispatch-0.6.0 networkx-1.11 numexpr-2.7.3 pandas-0.22.0 pandas-datareader-0.8.1 patsy-0.5.1 python-interface-1.6.0 sortedcontainers-2.3.0 statsmodels-0.12.2 tables-3.6.1 toolz-0.11.1 trading-calendars-2.1.1 zipline-1.4.1
root@af475e1422f9:/home# python main.py --mode=train
==============Start Fetching Data===========
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/opt/conda/lib/python3.6/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/opt/conda/lib/python3.6/site-packages/yfinance/base.py", line 226, in history
    df = _pd.concat([quotes, dividends, splits], axis=1, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'
```

**Comment by Homme769** [comment]
same question

**Comment by IhCosmo** [comment]
same question with python 3.7

**Comment by XiaoYangLiu-FinRL** [comment]
main.py is updated.  
https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/main.py
