### ISSUE TITLE
ValueError: cannot copy sequence with size 292 to array axis with dimension 301

### ISSUE THREAD

**Issue by CSVStorage** [AI4Finance-Foundation/FinRL#222]
Hi,
I installed finrl library following the Bare-metal installation guide in README file.
When I run 
```console
python main.py --mode=train 
```
I get the following error:

```python
/usr/local/lib/python3.7/dist-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; multipliers will not be applied'
==============Start Fetching Data===========
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (156457, 8)
==============Start Feature Engineering===========
Successfully added technical indicators
Successfully added turbulence index
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "/content/FinRL-Library/finrl/autotrain/training.py", line 67, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "/content/FinRL-Library/finrl/env/env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: cannot copy sequence with size 292 to array axis with dimension 301
```
<br>
I don't know if is a bug or I am doing something wrongly, can you help me?

**Comment by kiennt23** [comment]
I have the same issue.

**Comment by jefferyanderson** [comment]
Same here @kiennt23 , @CSVStorage

**Comment by dumbretard69** [comment]
same here

**Comment by weileze** [comment]
same here

**Comment by destinyyzy** [comment]
+1

**Comment by ruichengHan** [comment]
+1

**Comment by ruichengHan** [comment]
I remove the "V" in DOW_30_TICKER in finrl/config/config.py and it works
maybe you can take a try.

DOW_30_TICKER = [
    "AAPL",
    "MSFT",
    "JPM",
 #   "V",  remove it 
    "RTX",
    "PG",
    "GS",
    "NKE",
    "DIS",
    "AXP",
    "HD",
    "INTC",
    "WMT",
    "IBM",
    "MRK",
    "UNH",
    "KO",
    "CAT",
    "TRV",
    "JNJ",
    "CVX",
    "MCD",
    "VZ",
    "CSCO",
    "XOM",
    "BA",
    "MMM",
    "PFE",
    "WBA",
    "DD",
]

**Comment by kiennt23** [comment]
> I remove the "V" in DOW_30_TICKER in finrl/config/config.py and it works
> maybe you can take a try.
> 
> DOW_30_TICKER = [
> "AAPL",
> "MSFT",
> "JPM",
> # "V", remove it
> "RTX",
> "PG",
> "GS",
> "NKE",
> "DIS",
> "AXP",
> "HD",
> "INTC",
> "WMT",
> "IBM",
> "MRK",
> "UNH",
> "KO",
> "CAT",
> "TRV",
> "JNJ",
> "CVX",
> "MCD",
> "VZ",
> "CSCO",
> "XOM",
> "BA",
> "MMM",
> "PFE",
> "WBA",
> "DD",
> ]

What is the reason for it? I think V is still in the list?
