### ISSUE TITLE
Issue with Alpaca

### ISSUE THREAD

**Issue by arnishow** [AI4Finance-Foundation/FinRL#286]
Hi,
I'm trying to play with AlpacaPaperTrading and this is my env: 
```
    "ticker_list" : TICKERS,
    "time_interval" : "5Min",
    "drl_lib" : "stable_baselines3",
    "agent" : "ppo",
    "cwd" : './' + config.TRAINED_MODEL_DIR + '/trained_ppo.zip',
    "net_dim" : 2 ** 9,
    "state_dim" : state_space,
    "action_dim" : stock_dimension,
    "API_KEY" : ALPACA_API_KEY,
    "API_SECRET" : ALPACA_API_SECRET,
    "APCA_API_BASE_URL" : ALPACA_API_URL,
    "tech_indicator_list" : TECHNICAL_INDICATORS_LIST,
    "turbulence_thresh" : 70,
    "max_stock" : PORTFOLIO_STOCK_HMAX,
    "latency" : None
```
and getting this error:
```
$ AlpacaPaperTrading.run(trade_env)

Waiting for market to open...
Market opened.
Succesfully add technical indicators
Successfully transformed into array
4

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/finrl/neo_finrl/env_stock_trading/env_stock_papertrading.py", line 197, in trade
    action = self.model.predict(state)[0]
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/base_class.py", line 540, in predict
    return self.policy.predict(observation, state, mask, deterministic)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/policies.py", line 323, in predict
    observation, vectorized_env = self.obs_to_tensor(observation)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/policies.py", line 240, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/utils.py", line 357, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/utils.py", line 242, in is_vectorized_box_observation
    + "or (n_env, {}) for the observation shape.".format(", ".join(map(str, observation_space.shape)))
ValueError: Error: Unexpected observation shape (47,) for Box environment, please use (41,) or (n_env, 41) for the observation shape.
```

What am I missing?
Thanks

**Comment by rayrui312** [comment]
I think this error is usually because the state dimension of the pre-trained agent is different from that in the environment. You may have a check.

**Comment by arnishow** [comment]
I'm must be dumb, this is what I have:
```
$ print(alpaca_kwargs)

{'ticker_list': ['AAPL', 'MSFT', 'AMZN', 'GOOGL'], 'time_interval': '5Min', 'drl_lib': 'stable_baselines3', 'agent': 'ppo', 'cwd': './trained_models/trained_ppo.zip', 'net_dim': 512, 'state_dim': 41, 'action_dim': 4, 'API_KEY': 'xxx', 'API_SECRET': 'xxx', 'APCA_API_BASE_URL': 'https://paper-api.alpaca.markets', 'tech_indicator_list': ['macd', 'boll_ub', 'boll_lb', 'rsi_30', 'cci_30', 'dx_30', 'close_30_sma', 'close_60_sma'], 'turbulence_thresh': 70, 'max_stock': 100, 'latency': None}

```
I have no idea how I get 47 dimensions here.

**Comment by rayrui312** [comment]
I have checked the state settings in AlpacaPaperTrading. The state is given by 
` state = np.hstack((amount,
                    turbulence,
                    self.turbulence_bool,
                    price * scale,
                    self.stocks * scale,
                    self.stocks_cd,
                    tech,
                    )).astype(np.float32)`
The state dimension should be 47 in this paper trading environment. 
1 (amount) + 1(turbulence) + 1(turbulence_bool) + 4(price) + 4(self.stocks) + 4(self.stocks_cd) + 4*8(tech) = 47.

So I think the problem is that the state settings in your training environment are different from those in the paper trading environment. You can change either one. As long as the environment settings in training and trading envs are the same, it should work.

**Comment by arnishow** [comment]
Thanks a lot, I missed that & it's all good now. Ty
