### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by sp3json** [AI4Finance-Foundation/FinRL#338]
I'm trying to run code from https://github.com/AI4Finance-Foundation/FinRL/blob/master/FinRL_PaperTrading_Demo.ipynb in virtual environment but there are some errors like this:

```bash
~# virtualenv -p python3 virt
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/test/virt/bin/python3
Also creating executable in /home/test/virt/bin/python

(virt) [test@lnx]$ python -V
Python 3.7.3
(virt) [test@lnx]$ pip -V
pip 21.3.1 from /home/test/virt/lib/python3.7/site-packages/pip (python 3.7)
```
Next i'm running virtual environment with Python 3
```
~# source virt/bin/activate
(virt) [test@lnx]$ pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git
Collecting git+https://github.com/AI4Finance-LLC/FinRL-Library.git
  Cloning https://github.com/AI4Finance-LLC/FinRL-Library.git to /tmp/pip-req-build-ka1tmxm6
  Running command git clone --filter=blob:none -q https://github.com/AI4Finance-LLC/FinRL-Library.git /tmp/pip-req-build-ka1tmxm6
  Resolved https://github.com/AI4Finance-LLC/FinRL-Library.git to commit ea0fdaf944ec30d4011e3f9d5626dee51090ece8
  Preparing metadata (setup.py) ... done
Collecting pyfolio@ git+https://github.com/quantopian/pyfolio.git#egg=pyfolio-0.9.2
  Cloning https://github.com/quantopian/pyfolio.git to /tmp/pip-install-26vy1si9/pyfolio_57b8c9a086474e1f92039378bc081b89
[...]
l-1.6.3 yfinance-0.1.64 zipp-3.6.0
```
source file
```python
from finrl.train import train
from finrl.test import test
from finrl.apps.config import DOW_30_TICKER
from finrl.apps.config import TECHNICAL_INDICATORS_LIST
from finrl.neo_finrl.env_stock_trading.env_stocktrading_np import StockTradingEnv
from finrl.neo_finrl.env_stock_trading.env_stock_papertrading import AlpacaPaperTrading
from finrl.neo_finrl.data_processor import DataProcessor
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

import numpy as np
import pandas as pd
```

```bash
(virt) [test@lnxl]$ python prototype_a.py
Traceback (most recent call last):
  File "prototype_a.py", line 1, in <module>
    from finrl.train import train
  File "/home/test/virt/lib/python3.7/site-packages/finrl/train.py", line 3, in <module>
    from finrl.drl_agents.rllib.models import DRLAgent as DRLAgent_rllib
  File "/home/test/virt/lib/python3.7/site-packages/finrl/drl_agents/rllib/models.py", line 3, in <module>
    from ray.rllib.agents.a3c import a2c
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/__init__.py", line 5, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/env/__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 4, in <module>
    from ray.rllib.env.external_env import ExternalEnv
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/env/external_env.py", line 7, in <module>
    from ray.rllib.utils.annotations import PublicAPI
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/utils/__init__.py", line 9, in <module>
    from ray.rllib.utils.numpy import sigmoid, softmax, relu, one_hot, fc, lstm, \
  File "/home/test/virt/lib/python3.7/site-packages/ray/rllib/utils/numpy.py", line 2, in <module>
    import tree  # pip install dm_tree
```

ok, install missing dependency `dm_tree`
```bash
(virt) [test@lnx]$ pip install dm_tree
Collecting dm_tree
  Using cached dm_tree-0.1.6-cp37-cp37m-manylinux_2_24_x86_64.whl (93 kB)
Requirement already satisfied: six>=1.12.0 in ./virt/lib/python3.7/site-packages (from dm_tree) (1.16.0)
Installing collected packages: dm-tree
```
Re-run
```bash
(virt) [m@lnx trade_rl]$ python prototype_a.py 
Traceback (most recent call last):
  File "prototype_a.py", line 1, in <module>
    from finrl.train import train
  File "/home/test/virt/lib/python3.7/site-packages/finrl/train.py", line 5, in <module>
    from finrl.neo_finrl.data_processor import DataProcessor
  File "/home/test/virt/lib/python3.7/site-packages/finrl/neo_finrl/data_processor.py", line 3, in <module>
    from finrl.neo_finrl.data_processors.processor_alpaca import AlpacaProcessor as Alpaca
  File "/home/test/virt/lib/python3.7/site-packages/finrl/neo_finrl/data_processors/processor_alpaca.py", line 5, in <module>
    import trading_calendars as tc
  File "/home/test/virt/lib/python3.7/site-packages/trading_calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/home/test/virt/lib/python3.7/site-packages/trading_calendars/trading_calendar.py", line 33, in <module>
    from .calendar_helpers import (
  File "/home/test/virt/lib/python3.7/site-packages/trading_calendars/calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'
```
so there is a new problem with `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'`

Please, need help.

BTW, I tried the same but using docker from here `https://github.com/AI4Finance-Foundation/FinRL/tree/master/docker` and problem is no longer there.
Maybe because in the image `stablebaselines/rl-baselines3-zoo:0.11.0a4` there are some additional dependencies? hmmm

**Comment by sp3json** [comment]
Now i tried a different method but i still have the same problem. What I did:
```bash
~# virtualenv -p python3 virt
~# source virt/bin/activate
~# git clone https://github.com/AI4Finance-Foundation/FinRL
~# pip install -r FinRL/requirements.txt -I
~# git clone https://github.com/AI4Finance-Foundation/ElegantRL
~# cd ElegantRL
~# pip install .
```
and similar effect

```bash
[...]
    import tree  # pip install dm_tree
ModuleNotFoundError: No module named 'tree'
~# pip install dm_tree
```
run python
```bash
~# python prototype_a.py
[...]
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'
```

**Comment by sp3json** [comment]
i found some clue https://stackoverflow.com/questions/68249890/np-nat-error-when-attempting-to-import-pandas-market-calender
```bash
(virt) [test@lnx]$ pip freeze | grep cal
trading-calendars==2.1.1
```
next

```bash
(virt) [test@lnx]$ pip install pandas==1.2.5
Collecting pandas==1.2.5
  Downloading pandas-1.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 7.7 MB/s            
Requirement already satisfied: pytz>=2017.3 in /home/test/virt/lib/python3.7/site-packages (from pandas==1.2.5) (2021.3)
Requirement already satisfied: numpy>=1.16.5 in /home/test/virt/lib/python3.7/site-packages (from pandas==1.2.5) (1.21.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/test/virt/lib/python3.7/site-packages (from pandas==1.2.5) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/test/virt/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas==1.2.5) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.4
    Uninstalling pandas-1.3.4:
      Successfully uninstalled pandas-1.3.4
Successfully installed pandas-1.2.5
(virt) [m@lnx FinRL]$ python prototype_a.py    
Traceback (most recent call last):
  File "prototype_a.py", line 8, in <module>
    from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline
  File "/home/test/virt/FinRL/finrl/plot.py", line 7, in <module>
    import pyfolio
ModuleNotFoundError: No module named 'pyfolio'
```

```bash
(virt) [test@lnx]$ pip install pyfolio
[...]
```
and finally

```bash
(virt) [test@lnx]$ python prototype_a.py 
/home/test/virt/lib/python3.7/site-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; mutltipliers will not be applied' +
```

So this solved problem?

**Comment by rayrui312** [comment]
This solved the problem. For the UserWarning of 'zipline.assets', you may see [issue#313](https://github.com/AI4Finance-Foundation/FinRL/issues/313).
