### ISSUE TITLE
json.errors.JSONDecodeError: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by HSLiu-Initial** [AI4Finance-Foundation/FinRL#398]
When I tried to dowload historic data in the notebook **FinRL_PortfolioAllocation_NeurIPS_2020.ipynb**, I get the following error message:
```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "E:\Anaconda\envs\finrl\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda\envs\finrl\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Anaconda\envs\finrl\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "E:\Anaconda\envs\finrl\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "E:\Anaconda\envs\finrl\lib\site-packages\yfinance\multi.py", line 181, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "E:\Anaconda\envs\finrl\lib\site-packages\yfinance\base.py", line 162, in history
    data = data.json()
  File "E:\Anaconda\envs\finrl\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\Anaconda\envs\finrl\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "E:\Anaconda\envs\finrl\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Anaconda\envs\finrl\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

the code is
```
df = YahooDownloader(start_date = '2008-01-01',
                     end_date = '2008-01-01',
                     ticker_list = ["AXP"]).fetch_data()
```

**Comment by zhumingpassional** [comment]
Please try download_data instead of fetch_data. https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/data_processors/processor_yahoofinance.py

In addition, if start_date == end_date, and the the day is not open, it raises an error. You can try end_date = '2008-03-01'

**Comment by HSLiu-Initial** [comment]
> Please try download_data instead of fetch_data. https://github.com/AI4Finance-Foundation/FinRL/blob/master/finrl/finrl_meta/data_processors/processor_yahoofinance.py
> 
> In addition, if start_date == end_date, and that day is not open, it raises an error. You can try end_date = '2008-03-01'

I have tried your suggestion but still got the same error.
Here is my code:
```
df = YahooFinanceProcessor().download_data(start_date='2008-01-01',
                                           end_date='2021-09-02',
                                           ticker_list=config.DOW_30_TICKER,
time_interval='1d')
```

**Comment by zhumingpassional** [comment]
time_interval == "1D"

**Comment by IntelSpectre** [comment]
Hi, I would appreciate any help withthe following error:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

My code from the tutorial is:

dp = YahooFinanceProcessor()
df = dp.download_data(start_date = '2008-01-01',
                     end_date = '2021-10-31',
                     ticker_list = config_tickers.DOW_30_TICKER, time_interval='1D')
