### ISSUE TITLE
Error in Paper Trading DEMO importing packages from elegant RL

### ISSUE THREAD

**Issue by FernandoDorado** [AI4Finance-Foundation/FinRL#441]
Hello, 

I have detected an error in the DEMO paper by importing an ElegantRL package. 

`/opt/conda/lib/python3.8/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
Traceback (most recent call last):
  File "production_agent.py", line 360, in <module>
    paper_trading_erl = AlpacaPaperTrading(ticker_list = MY_TICKER, 
  File "production_agent.py", line 53, in __init__
    from elegantrl.run import Arguments, init_agent`

This has been solved by importing this class from another file: `elegant.config import Arguments`, in case you can fix it from this notebook.

**Comment by FernandoDorado** [comment]
I just created a PR fixing this bug, if you want to check it or merge it. 

https://github.com/AI4Finance-Foundation/FinRL/pull/442

**Comment by FernandoDorado** [comment]
Merged!

**Comment by rayrui312** [comment]
Thanks!
