### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by IntelSpectre** [AI4Finance-Foundation/FinRL#563]
When executing the following code:

dp = YahooFinanceProcessor()
df = dp.download_data(start_date = '2008-01-01',
                     end_date = '2021-10-31',
                     ticker_list = config_tickers.DOW_30_TICKER, time_interval='1D')

I receive the following error:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/deepintel/opt/anaconda3/envs/cv-nd/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks for the help

**Comment by rayrui312** [comment]
I have just tested the notebook on Colab and didn't replicate this error. I think there is no problem with our codes. This error is raised from 'yfinance' package, which is usually caused by the wrong data format. From your error info, it seems that the downloading function from 'yfinance' returned 'None'.

**Comment by IntelSpectre** [comment]
Ok thanks, my internet connections seem fine, but I will try running this on colab instead.
