### ISSUE TITLE
KeyError on FinRL_PaperTrading_Demo

### ISSUE THREAD

**Issue by bryan-sullivan** [AI4Finance-Foundation/FinRL#627]
I have been working through the notebooks and after the models train, I'm getting keyerrors on the tickers.  Here is the full error:

```
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'AXP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/hd/q4f2fld15rddypk_jtxfv54r0000gn/T/ipykernel_70574/148776005.py", line 186, in trade
  File "/var/folders/hd/q4f2fld15rddypk_jtxfv54r0000gn/T/ipykernel_70574/148776005.py", line 250, in get_state
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/site-packages/finrl/finrl_meta/data_processors/processor_alpaca.py", line 273, in fetch_latest_data
    barset = self.api.get_bars([tic], time_interval, limit=limit).df[tic]
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/bryansullivan/opt/anaconda3/envs/spyder-env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'AXP'
```

The call is unchanged from the default:

```
paper_trading_erl = AlpacaPaperTrading(ticker_list = DOW_30_TICKER, 
                                       time_interval = '1Min', 
                                       drl_lib = 'elegantrl', 
                                       agent = 'ppo', 
                                       cwd = './papertrading_erl_retrain', 
                                       net_dim = 512, 
                                       state_dim = state_dim, 
                                       action_dim= action_dim, 
                                       API_KEY = API_KEY, 
                                       API_SECRET = API_SECRET, 
                                       API_BASE_URL = API_BASE_URL, 
                                       tech_indicator_list = INDICATORS, 
                                       turbulence_thresh=30, 
                                       max_stock=1e2,
                                )
paper_trading_erl.run()
```

I confirmed the DOW_30_TICKER is a list and unchanged but can't get around this error.

**Comment by dev590t** [comment]
this https://github.com/AI4Finance-Foundation/FinRL/pull/619 should normally solve your problem

**Comment by bryan-sullivan** [comment]
This did correct the keyerror issue.  I'm getting qty of 9223372036854775808 for the orders which is something to continue to review.  For example, when the market opens, I get messages like this for every order:

**Comment by dev590t** [comment]
Sometime, I get also this error. But sometime the error doesn't appear. I don't know why

**Comment by bryan-sullivan** [comment]
Was able to execute today without error.
