### ISSUE TITLE
TypeError when running "python main.py --mode=train" command 

### ISSUE THREAD

**Issue by varunpan** [AI4Finance-Foundation/FinRL#648]
**Describe the bug**
Im getting an error when running "python main.py --mode=train" command. See below for for the full error traceback:
```
Traceback (most recent call last):
  File "/Users/varunpanchal/Documents/Projects/FinRLVP/FinRL/finrl/main.py", line 146, in <module>
    raise SystemExit(main())
  File "/Users/varunpanchal/Documents/Projects/FinRLVP/FinRL/finrl/main.py", line 71, in main
    train(
  File "/Users/varunpanchal/miniforge3/envs/finrlvp/lib/python3.9/site-packages/finrl/train.py", line 60, in train
    trained_model = agent.train_model(
  File "/Users/varunpanchal/miniforge3/envs/finrlvp/lib/python3.9/site-packages/finrl/agents/elegantrl/models.py", line 78, in train_model
    train_and_evaluate(model)
  File "/Users/varunpanchal/miniforge3/envs/finrlvp/lib/python3.9/site-packages/elegantrl/train/run.py", line 58, in train_and_evaluate
    agent = init_agent(args, gpu_id, env)
  File "/Users/varunpanchal/miniforge3/envs/finrlvp/lib/python3.9/site-packages/elegantrl/train/run.py", line 13, in init_agent
    agent = args.agent(args.net_dim, args.state_dim, args.action_dim, gpu_id=gpu_id, args=args)
TypeError: 'module' object is not callable
```

**To Reproduce**
1. run `python main.py --mode=train`

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Python: 3.9

**Comment by zhumingpassional** [comment]
Thanks for reporting it. 

fixed.

**Comment by varunpan** [comment]
This is error is fixed. Im getting another error. Will create a separate issues for it
