### ISSUE TITLE
Not able to run the first file

### ISSUE THREAD

**Issue by GirishKumarSharma** [AI4Finance-Foundation/FinRL#730]
`girish@pc1804:~$ lsb_release -a`
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 18.04.6 LTS`
`Release:	18.04`
`Codename:	bionic`
`girish@pc1804:~$ python --version`
`Python 3.6.5 :: Anaconda, Inc.`
`girish@pc1804:~$ `
` `
`girish@pc1804:~$ source activate finrl`
`(finrl) girish@pc1804:~$ jupyter notebook`

`http://localhost:8888/notebooks/FinRL/tutorials/1-Introduction/Stock_Fundamental.ipynb`

`## install finrl library`
`!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git`

is returning below error : 

`Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git`
`  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-75ppc0wj`
`    Complete output from command python setup.py egg_info:`
`    Traceback (most recent call last):`
`      File "<string>", line 1, in <module>`
`      File "/tmp/pip-req-build-75ppc0wj/setup.py", line 1`
`        from __future__ import annotations`
`        ^`
`    SyntaxError: future feature annotations is not defined`
` `    
`    ----------------------------------------`
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-75ppc0wj/`
`You are using pip version 10.0.1, however version 21.3.1 is available.`
`You should consider upgrading via the 'pip install --upgrade pip' command.`

When I checks /tmp folder there is no pip-req-build-75ppc0wj folder exists.

**Comment by lcavalie** [comment]
Looks like your environment is not up to date at all (pip), I would recommend to start by an overall update and see if the problem remains.

**Comment by GirishKumarSharma** [comment]
Will you please mention which Python, Pip and all required packages version along with OS info, you are using. I will clone my environment as you mention please.

**Comment by zhumingpassional** [comment]
pls open the file by clicking the "colab" icon.
