### ISSUE TITLE
Runtime error:  if zone.upper() == 'UTC': AttributeError: 'numpy.float64' object has no attribute 'upper'

### ISSUE THREAD

**Issue by guo-li-hua** [AI4Finance-Foundation/FinRL#759]
**Describe the bug**
first run Stock_NeurIPS2018_SB3.py  error

**To Reproduce**
cmd run :python  Stock_NeurIPS2018_SB3.py

**Screenshots**
(AI4Finance) D:\GoData\src\github.com\AI4Finance-Foundation\FinRL>python  Stock_NeurIPS2018_SB3.py
D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\pyfolio\pos.py:26: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\yfinance\multi.py", line 199, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\yfinance\multi.py", line 213, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\yfinance\base.py", line 168, in history
    end = utils._parse_user_dt(end, tz)
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\yfinance\utils.py", line 157, in _parse_user_dt
    dt = _tz.timezone(exchange_tz).localize(dt)
  File "D:\ProgramData\Anaconda3\envs\AI4Finance\lib\site-packages\pytz\__init__.py", line 170, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'numpy.float64' object has no attribute 'upper'

**Comment by guo-li-hua** [comment]
The startup thread uses library files. How can I solve this problem and what causes it?

**Comment by Athe-kunal** [comment]
Hi @guo-li-hua 
Can you try to update pytz package?

**Comment by guo-li-hua** [comment]
(AI4Finance) D:\>pip install --upgrade pytz
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pytz in d:\programdata\anaconda3\envs\ai4finance\lib\site-packages (2022.6)

The pytz is already the latest version。

**Comment by guo-li-hua** [comment]
In addition, it is found that every time this problem occurs, the Stock_NeurIPS2018_SB3.ipynb  is recovered normally without error，why

**Comment by zhumingpassional** [comment]
@guo-li-hua  
Are you in China? have you used vpn?
pls run the corresponding .pynb first, whose server is in foreign countries.

**Comment by guo-li-hua** [comment]
>
Yes, if I use vpn to run Stock_NeurIPS2018_SB3.py in China, how should I set？thanks

**Comment by guo-li-hua** [comment]
![image](https://user-images.githubusercontent.com/34728163/200241585-cd91c3e2-c153-4fc3-9144-29e99362999b.png)

**Comment by guo-li-hua** [comment]
def _get_ticker_tz(self, debug_mode, proxy, timeout):
        if not self._tz is None:
            return self._tz   **----->is None at first，now is Nan**
        tkr_tz = utils.cache_lookup_tkr_tz(self.ticker)
        if tkr_tz is None :
            tkr_tz = self._fetch_ticker_tz(debug_mode, proxy, timeout)

so , is a bug  。 Automatically convert none to nan with pandas
