### ISSUE TITLE
TypeError: ActorPPO.__init__() missing 1 required positional argument: 'action_dim'

### ISSUE THREAD

**Issue by khanhphan1311** [AI4Finance-Foundation/FinRL#777]
I got this error after run "python main.py --mode=train"

```
Traceback (most recent call last):
  
File "D:\1. APPS\PyCharm\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  
File "D:\1. APPS\PyCharm\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  
File "D:\DATABASE\8_simplize_rl\FinRL\finrl\main.py", line 149, in <module>
    raise SystemExit(main())
  
File "D:\DATABASE\8_simplize_rl\FinRL\finrl\main.py", line 68, in main
    train(
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\finrl\train.py", line 60, in train
    trained_model = agent.train_model(
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\finrl\agents\elegantrl\models.py", line 84, in train_model
    train_and_evaluate(model)
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\elegantrl\train\run.py", line 87, in train_and_evaluate
    agent = init_agent(args, gpu_id, env)
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\elegantrl\train\run.py", line 16, in init_agent
    agent = args.agent_class(args.net_dim, args.state_dim, args.action_dim, gpu_id=gpu_id, args=args)
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\elegantrl\agents\AgentPPO.py", line 38, in __init__
    AgentBase.__init__(self, net_dim, state_dim, action_dim, gpu_id, args)
  
File "D:\1. APPS\Anaconda\envs\8_simplize_finrl\lib\site-packages\elegantrl\agents\AgentBase.py", line 53, in __init__
    self.act = act_class(net_dim, state_dim, action_dim).to(self.device)

TypeError: ActorPPO.__init__() missing 1 required positional argument: 'action_dim'
```

**Comment by mjp152** [comment]
Same problem

**Comment by khanhphan1311** [comment]
I found that:
In elegantrl > agents > net.py, init method is:
```
class ActorPPO(nn.Module):
    def __init__(self, mid_dim: int, num_layer: int, state_dim: int, action_dim: int):
        super().__init__()
```
But in elegantrl > agents > AgentBase.py:
```
act_class = getattr(self, "act_class", None)
self.act = act_class(net_dim, state_dim, action_dim).to(self.device)
```
In fact, we need 4 args if we want to use elegantrl.agents.net.ActorPPO

Are there any solutions for this, please?

**Comment by zhumingpassional** [comment]
recently, elegantrl is updated frequently. If s is urgent, pls choose other libs, e.g., stable baselines 3.
