### ISSUE TITLE
FinRL Erroreneous 

### ISSUE THREAD

**Issue by zillionsinternational** [AI4Finance-Foundation/FinRL#979]
Received two errors trying to run main.py under FinRL 

**1) Failed download:**
- AXP: No data found for this date range, symbol may be delisted

**2) ValueError: wrong time_interval**
Traceback (most recent call last):
  File "/Users/*/FinRL/finrl/main.py", line 149, in <module>
    raise SystemExit(main())
  File "/Users/*/FinRL/finrl/main.py", line 68, in main
    train(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/finrl/train.py", line 35, in train
    data = dp.add_vix(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/finrl/meta/data_processor.py", line 62, in add_vix
    df = self.processor.add_vix(df)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/finrl/meta/data_processors/processor_yahoofinance.py", line 263, in add_vix
    vix_df = self.download_data(["VIXY"], self.start, self.end, self.time_interval)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/finrl/meta/data_processors/processor_yahoofinance.py", line 84, in download_data
    time_interval = self.convert_interval(time_interval)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/finrl/meta/data_processors/processor_yahoofinance.py", line 77, in convert_interval
    raise ValueError("wrong time_interval")
ValueError: wrong time_interval

**Comment by zillionsinternational** [comment]
![Screenshot 2023-04-11 at 1 23 41 PM](https://user-images.githubusercontent.com/79404664/231063925-af5925d6-4ce9-459d-a2e1-6ad1f383043e.png)
